version: '3'
services:
  web-app:
    build: .
    ports:
      - "9000:9000"
    environment:
      - APPLICATION_SECRET
  postgres:
    image: postgres
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.1
