version: '3'
services:
  web-app:
    build: .
    ports:
      - "9000:9000"
    links:
      - postgres
      - elasticsearch
    environment:
      - APPLICATION_SECRET
  postgres:
    image: postgres
  elasticsearch:
    image: dmytroorlov/elasticsearch:2.2.2
